variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dcom.vaadin.testbench.Parameters.hubHostname=hub"
  # set the hub hostname to selenium nodes
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#available-settings-for-services
  # GitLab Runner 0.5.0 and up passes all YAML-defined variables to the created service containers.
  HUB_HOST: hub

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
  - .m2/repository

# This will only validate and compile stuff and run e.g. maven-enforcer-plugin.
# Because some enforcer rules might check dependency convergence and class duplications
# we use `test-compile` here instead of `validate`, so the correct classpath is picked up.
.validate: &validate
  stage: build
  script:
  - 'mvn $MAVEN_CLI_OPTS test-compile'

# For merge requests do not `deploy` but only run `verify`.
# See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
.verify: &verify
  stage: test
  script:
  - 'mvn $MAVEN_CLI_OPTS verify'
  except:
  - master

# Validate merge requests using JDK10
validate:jdk10:
  <<: *validate
  image: maven:3.5.4-jdk-10

# Verify merge requests using JDK10
verify:jdk10:
  <<: *verify
  image: maven:3.5.4-jdk-10
  services:
  - name: selenium/hub:3.141.59-mercury
    alias: hub
  - selenium/node-chrome:3.141.59-mercury