variables:
  # Any variables here will be set to the enviroment the containers run in.
  # e.g. MAVEN_OPTS environment variable will be used by any Maven commands

  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # This first defines sane defaults for CI style running. Then there is two TestBench specific system properties:
  # com.vaadin.testbench.Parameters.hubHostname - this must match the alias (hostname) of the selenium standalone service
  # vaadin.proKey - read the value from $VAADIN_PRO_KEY to not store secrets in the repo. The value is set via GitLab: Settings -> CI / CD -> Environment variables -> Variable key: VAADIN_PRO_KEY
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dcom.vaadin.testbench.Parameters.hubHostname=selenium-standalone-chrome -Dvaadin.proKey=$VAADIN_PRO_KEY"

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
  - .m2/repository

# Use Maven Docker image to run the builds
image: maven:3.6-jdk-12

# Define pipeline stages
stages:
  - build
  - test

# Runs mvn test-compile in the build stage. If return value is zero, job is considered to be passing
build:
  stage: build
  script:
  - 'mvn $MAVEN_CLI_OPTS test-compile'

# Runs mvn verify in the test stage. If return value is zero, job is considered to be passing
verify:
  stage: test
  script:
    - 'mvn --activate-profiles=gitlab-it $MAVEN_CLI_OPTS verify'
  services:
    # this image fires up a remotely drivable chrome on port 4444 on startup
    - name: selenium/standalone-chrome:3.141.59-mercury
      # and we give it a known DNS alias in order to tell testbench where it can be found
      alias: selenium-standalone-chrome